lovecal/lovecal/urls.py
from django.contrib import admin
from django.urls import path
from calculator import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.home,name='home'),

]

lovecal/calculator/models.py
from django.db import models

# Create your models here.
class Valentine(models.Model):
    name=models.CharField(max_length=20,blank=False)
    crush=models.CharField(max_length=20,blank=False)
    score=models.CharField(max_length=100,blank=False)

    def __str__(self):
        return self.name

lovecal/calculator/forms.py
from django import forms
from .models import Valentine

class Valentineform(forms.ModelForm):
    class Meta:
        model=Valentine
        fields=('crush','name')

lovecal/calculator/views.py
from django.shortcuts import render
from .models import Valentine
from .forms import Valentineform
import random
# Create your views here.

def home(request):
    if request.method=='POST':
        form =Valentineform(request.POST)

        if form.is_valid():
            valen=form.save(commit=False)
            if valen.name.lower()!='sreedhar':
                print(valen.name)
                valen.score=random.randint(0,100)
                form.save()
            else:
                error='wow you tried typing my name !'

            
    else:
        form=Valentineform()
    valentine_now=Valentine.objects.all()
    return render(request,'valentine_template/valentinespecial.html',{'form':form,'valentines':valentine_now})



lovecal/calculator/templates/valentine_template/valentinespecial.html

<!DOCTYPE html>
<html>
<title>We</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
h1,h2,h3,h4,h5,h6 {font-family: "Oswald"}
body {font-family: "Open Sans"}
</style>
<body class="w3-light-grey">

<!-- Navigation bar with social media icons -->
<div class="w3-bar w3-black w3-hide-small">
  <a href="#" class="w3-bar-item w3-button"><i class="fa fa-facebook-official"></i></a>
  <a href="#" class="w3-bar-item w3-button"><i class="fa fa-instagram"></i></a>
  <a href="#" class="w3-bar-item w3-button"><i class="fa fa-snapchat"></i></a>
  <a href="#" class="w3-bar-item w3-button"><i class="fa fa-flickr"></i></a>
  <a href="#" class="w3-bar-item w3-button"><i class="fa fa-twitter"></i></a>
  <a href="#" class="w3-bar-item w3-button"><i class="fa fa-linkedin"></i></a>
  <a href="#" class="w3-bar-item w3-button w3-right"><i class="fa fa-search"></i></a>
</div>

<!-- w3-content defines a container for fixed size centered content,
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1600px">

  <!-- Header -->
  <header class="w3-container w3-center w3-padding-48 w3-white">
    <h1 class="w3-xxxlarge"><b>Valentine's Day Special</b></h1>
    <h6>Welcome to the <span class="w3-tag">Love Calculator</span></h6>
  </header>

  <!-- Image header -->
  <header class="w3-display-container w3-wide" id="home">
    <img class="w3-image" src="https://img.freepik.com/free-vector/gift-box-with-heart-balloon-floating-it-sky-happy-valentine-s-day-banners-paper-art-style_43880-310.jpg?size=626&ext=jpg" alt="Fashion Blog" width="1600" height="1060">
    <div class="w3-display-left w3-padding-large">
      <h1 class="w3-text-white">It's Valentine's Day</h1>
      <h1 class="w3-jumbo w3-text-white w3-hide-small"><b>FIND HOW MUCH YOUR CRUSH LOVES YOU</b></h1>
      <h6><button class="w3-button w3-white w3-padding-large w3-large w3-opacity w3-hover-opacity-off" onclick="document.getElementById('subscribe').style.display='block'">Start</button></h6>
    </div>
  </header>

      <hr>
      <!-- Subscribe -->
      <div class="w3-white w3-margin">
        <div class="w3-container w3-padding w3-black">
          <h4></h4>
        </div>
        <div class="w3-container w3-white">
          <p>Find out how much your crush loves you !</p>
          <p><button type="button" onclick="document.getElementById('subscribe').style.display='block'" class="w3-button w3-block w3-red">Get Started</button></p>
        </div>
      </div>

      <!-- Posts -->
      <div class="w3-white w3-margin">
        <div class="w3-container w3-padding w3-black">
          <h4>Recent</h4>
        </div>
        <ul class="w3-ul w3-hoverable w3-white">
            {%for j in valentines%}
          <li class="w3-padding-16">
            <img src="/w3images/avatar_smoke.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px">
            <span class="w3-large">{{j.name}}</span>
            <br>
            <span>{{j.crush}} score {{j.score}}</span>
          </li>
           {%endfor%}

        </ul>
      </div>
      <hr>

      <!-- Advertising --

      <div class="w3-white w3-margin">
        <div class="w3-container w3-padding w3-black">
          <h4>Advertise</h4>
        </div>
        <div class="w3-container w3-white">
          <div class="w3-container w3-display-container w3-light-grey w3-section" style="height:200px">
            <span class="w3-display-middle">Your AD Here</span>
          </div>
        </div>
      </div>
      <hr>>




    <!-- END About/Intro Menu -->
    </div>

  <!-- END GRID -->
  </div>

<!-- END w3-content -->
</div>

<!-- Subscribe Modal -->
<div id="subscribe" class="w3-modal w3-animate-opacity">
  <div class="w3-modal-content" style="padding:32px">
    <div class="w3-container w3-white">
      <i onclick="document.getElementById('subscribe').style.display='none'" class="fa fa-remove w3-transparent w3-button w3-xlarge w3-right"></i>
      <h2 class="w3-wide">Love Prediction!</h2>
      <p>Your name and cursh's name including score will appear on the website!</p>
      <form method="post">
      {% csrf_token %}
      <p><input type="text" class="w3-input w3-border" name="crush" placeholder="Enter Crush Name" maxlength="20" required="" id="id_crush"></p>
      <p><input type="text" class="w3-input w3-border" name="name" placeholder="Enter your Name" maxlength="20" required="" id="id_name"></p>
      <input type="submit" class="w3-button w3-block w3-padding-large w3-red w3-margin-bottom" value="Submit">



          {% for error in field.errors %}
              <p style="color: red;">{{ error.field }}</p>
        {% endfor %}
      </form>

    </div>
  </div>
</div>

<!-- Footer -->
<footer class="w3-container w3-dark-grey" style="padding:32px">
  <a href="#" class="w3-button w3-black w3-padding-large w3-margin-bottom"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
  <p>This website is developed just for fun
     Dont misuse the platform
     Recent data will be displayed so be aware of the names you type in as it cannot be deleted !
  </p>
</footer>

<script>
// Toggle between hiding and showing blog replies/comments
document.getElementById("myBtn").click();
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

function likeFunction(x) {
  x.style.fontWeight = "bold";
  x.innerHTML = "✓ Liked";
}
</script>

</body>
</html>